name: EkidenSys
version: '0.001b'
main: com.github.nosh11.ekidensys.EkidenSys
api-version: '1.20'

depend:
    - Citizens

commands:
    session:
        description: "Course Plugin daze"
    ekiden:
        aliases: "ek"
        description: "Ekiden"
    team:
        description: "Team"